FROM centos

# install required softwares
RUN yum -y install gcc-c++

# copy required files
RUN mkdir /src
RUN mkdir /data
ADD analysis.cpp /src/analysis.cpp

# build
RUN g++ /src/analysis.cpp -std=c++11 -o /src/analysis

WORKDIR /src

# enrtypoint
CMD /src/analysis < /data/input > /data/output