var data = {
"nodes": [
	{"id": "I Kotenko", "group": 5, size: 36},
	{"id": "A Chechulin", "group": 2, size: 15},
	{"id": "E Doynikova", "group": 0, size: 5},
	{"id": "M Stepashkin", "group": 0, size: 10},
	{"id": "V Bogdanov", "group": 0, size: 4},
	{"id": "Steven Noel", "group": 4, size: 17},
	{"id": "Sushil Jajodia", "group": 4, size: 18},
	{"id": "Lingyu Wang", "group": 0, size: 6},
	{"id": "Tania Islam", "group": 0, size: 5},
	{"id": "Tao Long", "group": 0, size: 4},
	{"id": "Anoop Singhal", "group": 0, size: 4},
	{"id": "Hussain M.J. Almohri", "group": 0, size: 6},
	{"id": "Layne T. Watson", "group": 0, size: 5},
	{"id": "Danfeng Yao", "group": 0, size: 4},
	{"id": "Xinming Ou", "group": 5, size: 42},
	{"id": "Su Zhang", "group": 5, size: 31},
	{"id": "Doina Caragea", "group": 0, size: 4},
	{"id": "Xinwen Zhang", "group": 0, size: 10},
	{"id": "Liqun Chen", "group": 0, size: 3},
	{"id": "Nigel Edwards", "group": 0, size: 2},
	{"id": "Jing Jin", "group": 0, size: 1},
	{"id": "Rui Zhuang", "group": 5, size: 28},
	{"id": "Alexandru G. Bardas", "group": 0, size: 5},
	{"id": "Scott A. DeLoach", "group": 5, size: 28},
	{"id": "Alex Bardas", "group": 0, size: 4},
	{"id": "John Homer", "group": 0, size: 6},
	{"id": "David A. Schmidt", "group": 0, size: 3},
	{"id": "Yanhui Du", "group": 0, size: 2},
	{"id": "S. Raj Rajagopalan", "group": 0, size: 1},
	{"id": "Justin Yackoski", "group": 0, size: 6},
	{"id": "K Durkota", "group": 5, size: 28},
	{"id": "V Lisy", "group": 4, size: 23},
	{"id": "B Bosansky", "group": 4, size: 16},
	{"id": "C Kiekintveld", "group": 2, size: 12},
	{"id": "J Cermak", "group": 0, size: 6},
	{"id": "M Pechoucek", "group": 0, size: 2},
],"links": [
{"source": "I Kotenko", "target": "A Chechulin","group": 0, "value": 3},
{"source": "I Kotenko", "target": "E Doynikova","group": 0, "value": 1},
{"source": "I Kotenko", "target": "M Stepashkin","group": 0, "value": 2},
{"source": "I Kotenko", "target": "V Bogdanov","group": 0, "value": 1},
{"source": "M Stepashkin", "target": "V Bogdanov","group": 0, "value": 1},
{"source": "Steven Noel", "target": "Sushil Jajodia","group": 0, "value": 3},
{"source": "Sushil Jajodia", "target": "Lingyu Wang","group": 0, "value": 1},
{"source": "Sushil Jajodia", "target": "Tania Islam","group": 0, "value": 1},
{"source": "Sushil Jajodia", "target": "Tao Long","group": 0, "value": 1},
{"source": "Sushil Jajodia", "target": "Anoop Singhal","group": 0, "value": 1},
{"source": "Lingyu Wang", "target": "Tania Islam","group": 0, "value": 1},
{"source": "Lingyu Wang", "target": "Tao Long","group": 0, "value": 1},
{"source": "Lingyu Wang", "target": "Anoop Singhal","group": 0, "value": 1},
{"source": "Tania Islam", "target": "Tao Long","group": 0, "value": 1},
{"source": "Tania Islam", "target": "Anoop Singhal","group": 0, "value": 1},
{"source": "Tao Long", "target": "Anoop Singhal","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "Xinming Ou","group": 0, "value": 2},
{"source": "Anoop Singhal", "target": "Su Zhang","group": 0, "value": 2},
{"source": "Anoop Singhal", "target": "Rui Zhuang","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "Scott A. DeLoach","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "Alex Bardas","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "John Homer","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "David A. Schmidt","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "Yanhui Du","group": 0, "value": 1},
{"source": "Anoop Singhal", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "Hussain M.J. Almohri", "target": "Layne T. Watson","group": 0, "value": 1},
{"source": "Hussain M.J. Almohri", "target": "Danfeng Yao","group": 0, "value": 1},
{"source": "Hussain M.J. Almohri", "target": "Xinming Ou","group": 0, "value": 1},
{"source": "Layne T. Watson", "target": "Danfeng Yao","group": 0, "value": 1},
{"source": "Layne T. Watson", "target": "Xinming Ou","group": 0, "value": 1},
{"source": "Danfeng Yao", "target": "Xinming Ou","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Su Zhang","group": 0, "value": 6},
{"source": "Xinming Ou", "target": "Doina Caragea","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Xinwen Zhang","group": 0, "value": 2},
{"source": "Xinming Ou", "target": "Liqun Chen","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Nigel Edwards","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Jing Jin","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Rui Zhuang","group": 0, "value": 5},
{"source": "Xinming Ou", "target": "Alexandru G. Bardas","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Scott A. DeLoach","group": 0, "value": 6},
{"source": "Xinming Ou", "target": "Alex Bardas","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "John Homer","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "David A. Schmidt","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Yanhui Du","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "Xinming Ou", "target": "Justin Yackoski","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Doina Caragea","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Xinwen Zhang","group": 0, "value": 2},
{"source": "Su Zhang", "target": "Liqun Chen","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Nigel Edwards","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Jing Jin","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Rui Zhuang","group": 0, "value": 2},
{"source": "Su Zhang", "target": "Scott A. DeLoach","group": 0, "value": 2},
{"source": "Su Zhang", "target": "Alex Bardas","group": 0, "value": 1},
{"source": "Su Zhang", "target": "John Homer","group": 0, "value": 1},
{"source": "Su Zhang", "target": "David A. Schmidt","group": 0, "value": 1},
{"source": "Su Zhang", "target": "Yanhui Du","group": 0, "value": 1},
{"source": "Su Zhang", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "Xinwen Zhang", "target": "Liqun Chen","group": 0, "value": 1},
{"source": "Xinwen Zhang", "target": "Nigel Edwards","group": 0, "value": 1},
{"source": "Xinwen Zhang", "target": "Jing Jin","group": 0, "value": 1},
{"source": "Liqun Chen", "target": "Nigel Edwards","group": 0, "value": 1},
{"source": "Liqun Chen", "target": "Jing Jin","group": 0, "value": 1},
{"source": "Nigel Edwards", "target": "Jing Jin","group": 0, "value": 1},
{"source": "Rui Zhuang", "target": "Alexandru G. Bardas","group": 0, "value": 1},
{"source": "Rui Zhuang", "target": "Scott A. DeLoach","group": 0, "value": 5},
{"source": "Rui Zhuang", "target": "Alex Bardas","group": 0, "value": 1},
{"source": "Alexandru G. Bardas", "target": "Scott A. DeLoach","group": 0, "value": 1},
{"source": "Scott A. DeLoach", "target": "Alex Bardas","group": 0, "value": 1},
{"source": "Scott A. DeLoach", "target": "Justin Yackoski","group": 0, "value": 1},
{"source": "John Homer", "target": "David A. Schmidt","group": 0, "value": 1},
{"source": "John Homer", "target": "Yanhui Du","group": 0, "value": 1},
{"source": "John Homer", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "David A. Schmidt", "target": "Yanhui Du","group": 0, "value": 1},
{"source": "David A. Schmidt", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "Yanhui Du", "target": "S. Raj Rajagopalan","group": 0, "value": 1},
{"source": "K Durkota", "target": "V Lisy","group": 0, "value": 5},
{"source": "K Durkota", "target": "B Bosansky","group": 0, "value": 4},
{"source": "K Durkota", "target": "C Kiekintveld","group": 0, "value": 4},
{"source": "K Durkota", "target": "J Cermak","group": 0, "value": 1},
{"source": "K Durkota", "target": "M Pechoucek","group": 0, "value": 1},
{"source": "V Lisy", "target": "B Bosansky","group": 0, "value": 4},
{"source": "V Lisy", "target": "C Kiekintveld","group": 0, "value": 4},
{"source": "V Lisy", "target": "J Cermak","group": 0, "value": 1},
{"source": "V Lisy", "target": "M Pechoucek","group": 0, "value": 1},
{"source": "B Bosansky", "target": "C Kiekintveld","group": 0, "value": 4},
{"source": "B Bosansky", "target": "J Cermak","group": 0, "value": 1},
{"source": "B Bosansky", "target": "M Pechoucek","group": 0, "value": 1},
{"source": "C Kiekintveld", "target": "J Cermak","group": 0, "value": 1},
{"source": "C Kiekintveld", "target": "M Pechoucek","group": 0, "value": 1},
]};
